# Generated by Django 2.0.1 on 2018-01-11 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='Entry',
        ),
    ]
