# Generated by Django 2.0.1 on 2018-01-12 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findshop', '0002_auto_20180110_2323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
