# Generated by Django 2.0.1 on 2018-01-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findshop', '0003_delete_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
